"""The AI voice library and the tuning constants for local/Apple TTS rendering.

Pure data: the catalogue of selectable voices plus the rate, gap and loudness
targets the renderers apply. No behaviour, so nothing here imports the app.
"""
from typing import Any, Dict, List

AI_AUDIO_VOICE_ROLES = {"host", "guest", "narrator"}
AI_AUDIO_DISCLOSURE = "This episode includes AI-generated voice audio."
PROOF_STUDIO_LOCAL_FILTER = "highpass=f=80,lowpass=f=12000,loudnorm=I=-16:TP=-1.5:LRA=11"
PROOF_STUDIO_APPLE_GAP_SECONDS = 1.0
PROOF_STUDIO_APPLE_NARRATIVE_GAP_SECONDS = 1.0
PROOF_STUDIO_APPLE_TARGET_PEAK_DBFS = -4.5
PROOF_STUDIO_APPLE_RATES = {
    "host": 100,
    "guest": 98,
    "narrator": 96,
}
PROOF_STUDIO_APPLE_NARRATIVE_RATES = {
    "host": 100,
    "guest": 98,
    "narrator": 96,
}
PROOF_STUDIO_APPLE_VOICES = {
    "host": ["Aman", "Daniel", "Alex"],
    "guest": ["Samantha", "Ava", "Victoria"],
    "narrator": ["Samantha", "Aman", "Alex"],
}
AI_PODCAST_VOICE_LIBRARY: List[Dict[str, Any]] = [
    {
        "id": "aman-warm-analyst",
        "name": "Aman",
        "gender": "male",
        "style": "warm analyst",
        "accent": "Indian English",
        "description": "Warm, steady, and trustworthy for education or finance.",
        "suggested_roles": ["host", "narrator"],
        "apple_voices": ["Aman", "Aman (English (India))"],
        "kokoro_voice": "am_michael",
        "openai_voice": "ash",
        "espeak": {"voice": "en-in+m3", "speed": "148", "pitch": "46", "amplitude": "142"},
        "rate_wpm": 110,
    },
    {
        "id": "rishi-clear-guide",
        "name": "Rishi",
        "gender": "male",
        "style": "clear guide",
        "accent": "Indian English",
        "description": "Crisp and composed for explainers and founder conversations.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Rishi"],
        "kokoro_voice": "am_adam",
        "openai_voice": "sage",
        "espeak": {"voice": "en-in+m2", "speed": "146", "pitch": "44", "amplitude": "142"},
        "rate_wpm": 112,
    },
    {
        "id": "daniel-calm-british",
        "name": "Daniel",
        "gender": "male",
        "style": "calm British host",
        "accent": "American English",
        "description": "Polished and calm for law, current affairs, and long-form analysis.",
        "suggested_roles": ["host", "narrator"],
        "apple_voices": ["Daniel"],
        "kokoro_voice": "bm_daniel",
        "openai_voice": "onyx",
        "espeak": {"voice": "en-gb+m3", "speed": "146", "pitch": "43", "amplitude": "140"},
        "rate_wpm": 112,
    },
    {
        "id": "reed-bright-teacher",
        "name": "Reed",
        "gender": "male",
        "style": "clear teacher",
        "accent": "warm Indian English",
        "description": "Friendly and articulate for practical tutorials.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Rishi"],
        "kokoro_voice": "am_michael",
        "openai_voice": "echo",
        "espeak": {"voice": "en-in+m2", "speed": "146", "pitch": "44", "amplitude": "142"},
        "rate_wpm": 112,
    },
    {
        "id": "eddy-casual-host",
        "name": "Eddy",
        "gender": "male",
        "style": "casual host",
        "accent": "warm Indian English",
        "description": "Conversational and approachable for creator-led shows.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Rishi"],
        "kokoro_voice": "am_adam",
        "openai_voice": "verse",
        "espeak": {"voice": "en-in+m2", "speed": "146", "pitch": "44", "amplitude": "142"},
        "rate_wpm": 112,
    },
    {
        "id": "rocko-energetic-host",
        "name": "Rocko",
        "gender": "male",
        "style": "energetic host",
        "accent": "American English",
        "description": "More energetic without rushing; useful for technology and startup topics.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Rocko (English (US))", "Rocko"],
        "kokoro_voice": "am_adam",
        "openai_voice": "ash",
        "espeak": {"voice": "en-us+m5", "speed": "152", "pitch": "52", "amplitude": "140"},
        "rate_wpm": 220,
    },
    {
        "id": "grandpa-wise-narrator",
        "name": "Grandpa",
        "gender": "male",
        "style": "wise narrator",
        "accent": "American English",
        "description": "Grounded and patient for reflective storytelling.",
        "suggested_roles": ["narrator", "guest"],
        "apple_voices": ["Grandpa (English (US))", "Grandpa"],
        "kokoro_voice": "am_michael",
        "openai_voice": "onyx",
        "espeak": {"voice": "en-us+m1", "speed": "138", "pitch": "38", "amplitude": "138"},
        "rate_wpm": 152,
    },
    {
        "id": "oliver-uk-commentator",
        "name": "Oliver",
        "gender": "male",
        "style": "UK commentator",
        "accent": "British English",
        "description": "Composed and conversational for business and current-affairs contrast.",
        "suggested_roles": ["guest", "narrator"],
        "apple_voices": ["Eddy (English (UK))"],
        "kokoro_voice": "bm_daniel",
        "openai_voice": "echo",
        "espeak": {"voice": "en-gb+m2", "speed": "148", "pitch": "45", "amplitude": "137"},
        "rate_wpm": 220,
    },
    {
        "id": "rowan-uk-analyst",
        "name": "Rowan",
        "gender": "male",
        "style": "UK analyst",
        "accent": "British English",
        "description": "Crisp, slightly brighter analyst voice for explainers.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Reed (English (UK))"],
        "kokoro_voice": "bm_daniel",
        "openai_voice": "sage",
        "espeak": {"voice": "en-gb+m3", "speed": "149", "pitch": "47", "amplitude": "138"},
        "rate_wpm": 162,
    },
    {
        "id": "roman-uk-host",
        "name": "Roman",
        "gender": "male",
        "style": "energetic host",
        "accent": "American English",
        "description": "Energetic but controlled for technology and startup discussions.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Rocko (English (US))", "Rocko"],
        "kokoro_voice": "am_adam",
        "openai_voice": "verse",
        "espeak": {"voice": "en-gb+m4", "speed": "150", "pitch": "50", "amplitude": "139"},
        "rate_wpm": 220,
    },
    {
        "id": "samantha-warm-cohost",
        "name": "Samantha",
        "gender": "female",
        "style": "warm co-host",
        "accent": "American English",
        "description": "Warm, clear, and easy to stay with for long listening.",
        "suggested_roles": ["host", "guest", "narrator"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_sarah",
        "openai_voice": "nova",
        "espeak": {"voice": "en-us+f3", "speed": "146", "pitch": "58", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "tara-bright-indian",
        "name": "Tara",
        "gender": "female",
        "style": "bright Indian host",
        "accent": "Indian English",
        "description": "Bright and precise for education, health, and creator shows.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_bella",
        "openai_voice": "coral",
        "espeak": {"voice": "en-in+f3", "speed": "146", "pitch": "59", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "flo-friendly-guide",
        "name": "Flo",
        "gender": "female",
        "style": "friendly guide",
        "accent": "American English",
        "description": "Friendly and modern for onboarding-style episodes.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Tara"],
        "kokoro_voice": "af_bella",
        "openai_voice": "shimmer",
        "espeak": {"voice": "en-us+f4", "speed": "148", "pitch": "61", "amplitude": "135"},
        "rate_wpm": 112,
    },
    {
        "id": "sandy-calm-educator",
        "name": "Sandy",
        "gender": "female",
        "style": "calm educator",
        "accent": "American English",
        "description": "Clear, relaxed, and teacherly for explainers.",
        "suggested_roles": ["host", "narrator"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_sarah",
        "openai_voice": "alloy",
        "espeak": {"voice": "en-us+f2", "speed": "144", "pitch": "57", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "shelley-story-host",
        "name": "Shelley",
        "gender": "female",
        "style": "story host",
        "accent": "American English",
        "description": "Expressive but controlled for narrative shows.",
        "suggested_roles": ["host", "narrator"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_sarah",
        "openai_voice": "nova",
        "espeak": {"voice": "en-us+f5", "speed": "143", "pitch": "60", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "grandma-reflective-narrator",
        "name": "Grandma",
        "gender": "female",
        "style": "reflective narrator",
        "accent": "American English",
        "description": "Patient and intimate for reflective narration.",
        "suggested_roles": ["narrator", "guest"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_bella",
        "openai_voice": "shimmer",
        "espeak": {"voice": "en-us+f1", "speed": "136", "pitch": "52", "amplitude": "134"},
        "rate_wpm": 112,
    },
    {
        "id": "karen-australian-guide",
        "name": "Karen",
        "gender": "female",
        "style": "Australian guide",
        "accent": "Australian English",
        "description": "Clean and composed for global business and environment shows.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Karen"],
        "kokoro_voice": "af_bella",
        "openai_voice": "coral",
        "espeak": {"voice": "en-au+f3", "speed": "145", "pitch": "57", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "moira-irish-storyteller",
        "name": "Moira",
        "gender": "female",
        "style": "reflective storyteller",
        "accent": "warm neutral English",
        "description": "Textured and warm for story-led episodes.",
        "suggested_roles": ["narrator", "guest"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_sarah",
        "openai_voice": "fable",
        "espeak": {"voice": "en-us+f3", "speed": "144", "pitch": "57", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "tessa-global-host",
        "name": "Tessa",
        "gender": "female",
        "style": "global host",
        "accent": "South African English",
        "description": "Distinctive and articulate for international topics.",
        "suggested_roles": ["host", "guest"],
        "apple_voices": ["Tessa"],
        "kokoro_voice": "af_bella",
        "openai_voice": "shimmer",
        "espeak": {"voice": "en+f3", "speed": "144", "pitch": "56", "amplitude": "136"},
        "rate_wpm": 112,
    },
    {
        "id": "fiona-british-guide",
        "name": "Fiona",
        "gender": "female",
        "style": "British guide",
        "accent": "British English",
        "description": "Friendly and precise for educational recaps and guided explainers.",
        "suggested_roles": ["host", "guest", "narrator"],
        "apple_voices": ["Samantha"],
        "kokoro_voice": "af_sarah",
        "openai_voice": "alloy",
        "espeak": {"voice": "en-gb+f2", "speed": "148", "pitch": "57", "amplitude": "136"},
        "rate_wpm": 112,
    },
]
AI_PODCAST_VOICE_BY_ID = {voice["id"]: voice for voice in AI_PODCAST_VOICE_LIBRARY}
